- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Delete
      aws_glue_trigger:
        state: absent
        name: gum

    - name: Create
      aws_glue_trigger:
        state: present
        name: mch-prod-mch_core-gum
        trigger_type: SCHEDULED
        schedule: "cron(45 6 * * ? *)"
        actions:
          - job_name: mch-prod-mch_core-gum
