- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Create
      aws_glue_trigger:
        state: present
        name: test
        trigger_type: ON_DEMAND
        actions:
          - name: aaa
